import type { RentalProduct } from "./types";

const now = "2026-03-07T00:00:00.000Z";
const defaultImage =
  "https://images.unsplash.com/photo-1556909211-36987daf7b4d?auto=format&fit=crop&w=1200&q=80";

type Seed = Omit<
  RentalProduct,
  | "slug"
  | "name"
  | "monthlyPrice"
  | "originalPrice"
  | "reviewCount"
  | "image"
  | "summary"
  | "contract"
  | "management"
  | "specs"
> & {
  image?: string;
  reviewCount?: number;
};

const toProduct = (seed: Seed): RentalProduct => ({
  ...seed,
  slug: seed.productId,
  name: seed.modelName,
  monthlyPrice: seed.promoFee,
  originalPrice: seed.monthlyFee,
  reviewCount: seed.reviewCount ?? 200,
  image: seed.image ?? defaultImage,
  summary: "계약 핵심 조건을 쉽게 비교할 수 있는 추천 상품",
  contract: `${seed.contractTotalMonth}개월`,
  management: seed.managementType === "visit" ? "방문관리" : "셀프관리",
  specs: [
    { label: "의무사용", value: `${seed.mandatoryUseMonth}개월` },
    { label: "계약기간", value: `${seed.contractTotalMonth}개월` },
    { label: "관리 방식", value: seed.managementType === "visit" ? "방문관리" : "셀프관리" },
  ],
});

const seeds: Seed[] = [
  {
    productId: "cwy-wp-001",
    brand: "코웨이",
    modelName: "아이콘 직수 냉온정수기 Lite",
    category: "water_purifier",
    monthlyFee: 31900,
    promoFee: 28900,
    promoDurationMonth: 12,
    postPromoFee: 31900,
    mandatoryUseMonth: 36,
    contractTotalMonth: 60,
    managementType: "visit",
    installFee: 0,
    removalFee: 50000,
    supportsMove: true,
    terminationRuleNote: "약정 내 해지 시 위약금이 발생할 수 있습니다.",
    features: ["cold", "hot", "purify"],
    sizeTier: "slim",
    stockStatus: "active",
    updatedAt: now,
    badge: "BEST",
  },
  {
    productId: "cwy-wp-002",
    brand: "코웨이",
    modelName: "아이콘 얼음정수기 Pro",
    category: "water_purifier",
    monthlyFee: 37900,
    promoFee: 33900,
    promoDurationMonth: 12,
    postPromoFee: 37900,
    mandatoryUseMonth: 48,
    contractTotalMonth: 72,
    managementType: "visit",
    installFee: 0,
    removalFee: 50000,
    supportsMove: true,
    terminationRuleNote: "약정 내 해지 시 위약금이 발생할 수 있습니다.",
    features: ["cold", "hot", "purify", "ice"],
    sizeTier: "slim",
    stockStatus: "active",
    updatedAt: now,
    badge: "인기",
  },
  {
    productId: "cwy-wp-005",
    brand: "코웨이",
    modelName: "아이콘 미니 셀프",
    category: "water_purifier",
    monthlyFee: 26900,
    promoFee: 24900,
    promoDurationMonth: 12,
    postPromoFee: 26900,
    mandatoryUseMonth: 36,
    contractTotalMonth: 48,
    managementType: "self",
    installFee: 0,
    removalFee: 45000,
    supportsMove: true,
    terminationRuleNote: "할인 종료 후 요금 인상 구간을 확인하세요.",
    features: ["cold", "purify"],
    sizeTier: "slim",
    stockStatus: "active",
    updatedAt: now,
    badge: "혜택",
  },
  {
    productId: "cwy-wp-008",
    brand: "코웨이",
    modelName: "직수 정수기 컴팩트",
    category: "water_purifier",
    monthlyFee: 24900,
    promoFee: 22900,
    promoDurationMonth: 12,
    postPromoFee: 24900,
    mandatoryUseMonth: 24,
    contractTotalMonth: 36,
    managementType: "self",
    installFee: 0,
    removalFee: 40000,
    supportsMove: true,
    terminationRuleNote: "짧은 약정이지만 해지 비용 조건을 확인하세요.",
    features: ["purify"],
    sizeTier: "slim",
    stockStatus: "active",
    updatedAt: now,
  },
  {
    productId: "skm-wp-011",
    brand: "SK매직",
    modelName: "올인원 직수 냉온정수기",
    category: "water_purifier",
    monthlyFee: 30900,
    promoFee: 27900,
    promoDurationMonth: 12,
    postPromoFee: 30900,
    mandatoryUseMonth: 36,
    contractTotalMonth: 60,
    managementType: "visit",
    installFee: 0,
    removalFee: 50000,
    supportsMove: true,
    terminationRuleNote: "약정 내 해지 시 반환금이 발생할 수 있습니다.",
    features: ["cold", "hot", "purify"],
    sizeTier: "standard",
    stockStatus: "active",
    updatedAt: now,
  },
  {
    productId: "skm-wp-013",
    brand: "SK매직",
    modelName: "스스로직수 정수기",
    category: "water_purifier",
    monthlyFee: 27900,
    promoFee: 24900,
    promoDurationMonth: 12,
    postPromoFee: 27900,
    mandatoryUseMonth: 36,
    contractTotalMonth: 48,
    managementType: "self",
    installFee: 0,
    removalFee: 50000,
    supportsMove: true,
    terminationRuleNote: "해지 전 설치/회수 비용을 확인하세요.",
    features: ["cold", "purify"],
    sizeTier: "slim",
    stockStatus: "active",
    updatedAt: now,
  },
  {
    productId: "skm-wp-018",
    brand: "SK매직",
    modelName: "얼음정수기 스탠다드",
    category: "water_purifier",
    monthlyFee: 38900,
    promoFee: 34900,
    promoDurationMonth: 12,
    postPromoFee: 38900,
    mandatoryUseMonth: 48,
    contractTotalMonth: 72,
    managementType: "visit",
    installFee: 0,
    removalFee: 55000,
    supportsMove: true,
    terminationRuleNote: "장기 약정형으로 중도해지 패널티를 꼭 확인하세요.",
    features: ["cold", "hot", "purify", "ice"],
    sizeTier: "large",
    stockStatus: "active",
    updatedAt: now,
    badge: "특가",
  },
  {
    productId: "ckc-wp-021",
    brand: "쿠쿠",
    modelName: "인앤아웃 직수 정수기 A",
    category: "water_purifier",
    monthlyFee: 21900,
    promoFee: 19900,
    promoDurationMonth: 12,
    postPromoFee: 21900,
    mandatoryUseMonth: 24,
    contractTotalMonth: 36,
    managementType: "visit",
    installFee: 0,
    removalFee: 35000,
    supportsMove: true,
    terminationRuleNote: "프로모션 종료 시 요금 변화를 확인하세요.",
    features: ["purify"],
    sizeTier: "slim",
    stockStatus: "active",
    updatedAt: now,
  },
  {
    productId: "ckc-wp-023",
    brand: "쿠쿠",
    modelName: "스팀 얼음정수기",
    category: "water_purifier",
    monthlyFee: 36900,
    promoFee: 32900,
    promoDurationMonth: 12,
    postPromoFee: 36900,
    mandatoryUseMonth: 48,
    contractTotalMonth: 72,
    managementType: "visit",
    installFee: 0,
    removalFee: 50000,
    supportsMove: true,
    terminationRuleNote: "의무사용기간과 계약기간을 구분해 확인하세요.",
    features: ["cold", "hot", "purify", "ice"],
    sizeTier: "large",
    stockStatus: "active",
    updatedAt: now,
  },
  {
    productId: "ckc-wp-027",
    brand: "쿠쿠",
    modelName: "셀프관리 스탠다드",
    category: "water_purifier",
    monthlyFee: 25900,
    promoFee: 22900,
    promoDurationMonth: 12,
    postPromoFee: 25900,
    mandatoryUseMonth: 36,
    contractTotalMonth: 48,
    managementType: "self",
    installFee: 0,
    removalFee: 40000,
    supportsMove: true,
    terminationRuleNote: "약정 내 해지 수수료가 발생할 수 있습니다.",
    features: ["cold", "hot", "purify"],
    sizeTier: "standard",
    stockStatus: "active",
    updatedAt: now,
  },
  {
    productId: "ckc-wp-028",
    brand: "쿠쿠",
    modelName: "방문관리 패밀리형",
    category: "water_purifier",
    monthlyFee: 32900,
    promoFee: 28900,
    promoDurationMonth: 12,
    postPromoFee: 32900,
    mandatoryUseMonth: 48,
    contractTotalMonth: 60,
    managementType: "visit",
    installFee: 0,
    removalFee: 50000,
    supportsMove: true,
    terminationRuleNote: "장기 의무사용기간이라 이사 계획이 있으면 주의가 필요합니다.",
    features: ["cold", "hot", "purify"],
    sizeTier: "large",
    stockStatus: "active",
    updatedAt: now,
  },
  {
    productId: "paused-wp-001",
    brand: "테스트",
    modelName: "일시중지 상품",
    category: "water_purifier",
    monthlyFee: 19900,
    promoFee: 17900,
    promoDurationMonth: 6,
    postPromoFee: 19900,
    mandatoryUseMonth: 24,
    contractTotalMonth: 36,
    managementType: "self",
    installFee: 0,
    removalFee: 30000,
    supportsMove: true,
    terminationRuleNote: "판매 중지 상품",
    features: ["purify"],
    sizeTier: "slim",
    stockStatus: "paused",
    updatedAt: now,
  },
];

export const rentalProducts: RentalProduct[] = seeds.map(toProduct);
